/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei';

const RoomModel = (props) => {
  const { nodes, materials } = useGLTF('models/room.glb');
  
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.desk.geometry} material={materials.desk_Material} position={[-21.135, 12.158, -37.822]} rotation={[0, Math.PI / 2, 0]} scale={10} />
      <mesh castShadow receiveShadow geometry={nodes.officechair.geometry} material={materials.officechair_Material} position={[-24.5, 11.09, -22.5]} scale={10} />
      <mesh castShadow receiveShadow geometry={nodes.monitor.geometry} material={materials.monitor_Material} position={[-24.517, 24.824, -41.5]} rotation={[-Math.PI, 0, -Math.PI]} scale={8} />
      <mesh castShadow receiveShadow geometry={nodes.keyboard.geometry} material={materials.keyboard_Material} position={[-24.5, 17.967, -34.036]} scale={2.98} />
      <mesh castShadow receiveShadow geometry={nodes.coffee.geometry} material={materials['coffee_Material.001']} position={[-38.741, 19.296, -31.5]} rotation={[-Math.PI, 0, -Math.PI]} scale={5.5} />
      <mesh castShadow receiveShadow geometry={nodes.mousepad.geometry} material={materials.mousepad_Material} position={[-11.5, 17.664, -34]} scale={3} />
      <mesh castShadow receiveShadow geometry={nodes.mouse.geometry} material={materials.mouse_Material} position={[-12.35, 18.554, -34.259]} scale={7} />
      <mesh castShadow receiveShadow geometry={nodes.metalpencilcup.geometry} material={materials.metalpencilcup_Material} position={[-6.5, 19.75, -44.185]} scale={7} />
      <mesh castShadow receiveShadow geometry={nodes.flowerpot.geometry} material={materials.flowerpot_Material} position={[-12.02, 20.087, -44]} scale={3.5} />
      <mesh castShadow receiveShadow geometry={nodes.notebook1.geometry} material={materials.notebook1_Material} position={[-38.476, 18.297, -42.38]} rotation={[0, -Math.PI / 2, 0]} scale={5}>
        <mesh castShadow receiveShadow geometry={nodes.eraser.geometry} material={materials.eraser_Material} position={[-0.045, 0.478, -0.405]} rotation={[Math.PI, -0.611, Math.PI]} scale={0.2} />
        <mesh castShadow receiveShadow geometry={nodes.eraser_Backup.geometry} material={materials.VCMat_C} position={[-0.045, 0.478, -0.405]} rotation={[Math.PI, -0.611, Math.PI]} scale={0.2} />
        <mesh castShadow receiveShadow geometry={nodes.notebook2.geometry} material={materials.notebook2_Material} position={[0, 0.193, 0.035]} rotation={[0, 0.401, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.pencil1.geometry} material={materials['pencil1_Material.001']} position={[0.393, 0.484, 0.103]} rotation={[0, 0.14, Math.PI / 5]} scale={0.1} />
        <mesh castShadow receiveShadow geometry={nodes.pencil2.geometry} material={materials.pencil2_Material} position={[-0.063, 0.484, 0.285]} rotation={[0, Math.PI / 9, Math.PI / 5]} scale={0.1} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.shelf.geometry} material={materials.shelf_Material} position={[25.919, 18.668, -41.985]} scale={10} />
      <mesh castShadow receiveShadow geometry={nodes.heart.geometry} material={materials.heart_Material} position={[26.248, 19.502, -40.98]} scale={4} />
      <mesh castShadow receiveShadow geometry={nodes.bear.geometry} material={materials.bear_Material} position={[32.199, 19.502, -41.446]} rotation={[-Math.PI, 0.262, -Math.PI]} scale={4.5} />
      <mesh castShadow receiveShadow geometry={nodes.raccoon.geometry} material={materials.raccoon_Material} position={[18.525, 11.503, -42.634]} rotation={[Math.PI, -0.262, Math.PI]} scale={4} />
      <mesh castShadow receiveShadow geometry={nodes.cable.geometry} material={materials.cable_Material} position={[23.873, 11.486, -42.305]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.5} />
      <mesh castShadow receiveShadow geometry={nodes.piano.geometry} material={materials.piano_Material} position={[31.185, 11.495, -42.15]} rotation={[-Math.PI, 0, -Math.PI]} scale={4.5} />
      <mesh castShadow receiveShadow geometry={nodes.ghostrug.geometry} material={materials.ghostrug_Material} position={[-23.833, -0.438, 14.809]} rotation={[-Math.PI, 0, -Math.PI]} scale={10} />
      <mesh castShadow receiveShadow geometry={nodes.kirbyrug.geometry} material={materials.kirbyrug_Material} position={[13.195, -0.427, -10.844]} rotation={[0, Math.PI / 2, 0]} scale={10} />
      <mesh castShadow receiveShadow geometry={nodes.micstand.geometry} material={materials.micstand_Material} position={[1.927, -0.492, -35.946]} rotation={[-Math.PI, Math.PI / 3, -Math.PI]} scale={10} />
      <mesh castShadow receiveShadow geometry={nodes.guitar.geometry} material={materials.guitar_Material} position={[43.966, -0.451, -29.865]} rotation={[Math.PI / 2, 1.449, -Math.PI / 2]} scale={10} />
      <mesh castShadow receiveShadow geometry={nodes.bed.geometry} material={materials['bed_Material.001']} position={[22.718, -0.714, 28.043]} rotation={[0, Math.PI / 2, 0]} scale={10} />
      <mesh castShadow receiveShadow geometry={nodes.shark.geometry} material={materials.shark_Material} position={[18.161, 10.557, 31.031]} rotation={[0, Math.PI / 3, 0]} scale={8.5} />
      <mesh castShadow receiveShadow geometry={nodes.bedsidetable.geometry} material={materials.bedsidetable_Material} position={[43.002, -0.601, 2.839]} rotation={[0, Math.PI / 2, 0]} scale={7} />
      <mesh castShadow receiveShadow geometry={nodes.pictures.geometry} material={materials.pictures_Material} position={[-38.979, 28.054, -47.5]} rotation={[Math.PI / 2, 0, 0]} scale={4.2} />
      <mesh castShadow receiveShadow geometry={nodes.room.geometry} material={materials.room_Material} position={[0.667, -5.409, 0.3]} rotation={[0, Math.PI / 2, 0]} scale={10} />
      <mesh castShadow receiveShadow geometry={nodes.bed_Backup.geometry} material={materials.bed_Material} position={[22.718, -0.714, 28.043]} rotation={[0, Math.PI / 2, 0]} scale={10} />
      <mesh castShadow receiveShadow geometry={nodes.camera.geometry} material={materials.camera_Material} position={[33.449, 37.224, -42.628]} rotation={[-Math.PI, 0.262, -Math.PI]} scale={10} />
      <mesh castShadow receiveShadow geometry={nodes.film_roll.geometry} material={materials['film roll_Material']} position={[24.485, 35.522, -42.973]} scale={2} />
      <mesh castShadow receiveShadow geometry={nodes.filmroll2.geometry} material={materials.filmroll2_Material} position={[26.957, 35.522, -41.016]} scale={2} />
      <mesh castShadow receiveShadow geometry={nodes.camera2.geometry} material={materials.camera2_Material} position={[19.38, 35.493, -41.618]} rotation={[Math.PI, -0.262, Math.PI]} scale={8} />
      <mesh castShadow receiveShadow geometry={nodes.books1.geometry} material={materials.books1_Material} position={[22.41, 30.04, -41.124]} rotation={[-Math.PI, 0, -Math.PI]} scale={3} />
      <mesh castShadow receiveShadow geometry={nodes.books2.geometry} material={materials.books2_Material} position={[31.798, 27.462, -40.581]} rotation={[-Math.PI, 0, -Math.PI]} scale={3} />
      <mesh castShadow receiveShadow geometry={nodes.earthlamp.geometry} material={materials.earthlamp_Material} position={[20.015, 22.258, -41.491]} rotation={[-Math.PI, 0, -Math.PI]} scale={5.5} />
      <group position={[47.5, 45, -6]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube68915.geometry} material={materials.Voxel_mat254} />
        <mesh castShadow receiveShadow geometry={nodes.Cube68915_1.geometry} material={materials.Voxel_mat247} />
        <mesh castShadow receiveShadow geometry={nodes.Cube68915_2.geometry} material={materials.Voxel_mat244} />
        <mesh castShadow receiveShadow geometry={nodes.Cube68915_3.geometry} material={materials.Voxel_mat240} />
        <mesh castShadow receiveShadow geometry={nodes.Cube68915_4.geometry} material={materials.Voxel_mat238} />
        <mesh castShadow receiveShadow geometry={nodes.Cube68915_5.geometry} material={materials.Voxel_mat249} />
        <mesh castShadow receiveShadow geometry={nodes.Cube68915_6.geometry} material={materials['Voxel_mat45.005']} />
      </group>
      <group position={[47.5, 32, -6]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube69060.geometry} material={materials.Voxel_mat35} />
        <mesh castShadow receiveShadow geometry={nodes.Cube69060_1.geometry} material={materials['Voxel_mat14.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube69060_2.geometry} material={materials.Voxel_mat195} />
        <mesh castShadow receiveShadow geometry={nodes.Cube69060_3.geometry} material={materials['Voxel_mat244.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube69060_4.geometry} material={materials['Voxel_mat53.012']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube69060_5.geometry} material={materials.Voxel_mat32} />
        <mesh castShadow receiveShadow geometry={nodes.Cube69060_6.geometry} material={materials['Voxel_mat1.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube69060_7.geometry} material={materials['Voxel_mat247.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube69060_8.geometry} material={materials['Voxel_mat18.001']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.bjork.geometry} material={materials['bjork_Material.001']} position={[47.5, 45, -19]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={10} />
      <mesh castShadow receiveShadow geometry={nodes.flyinglotus.geometry} material={materials.flyinglotus_Material} position={[47.5, 32, -19]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={10} />
      <mesh castShadow receiveShadow geometry={nodes.catmeme.geometry} material={materials.catmeme_Material} position={[47.5, 48, 26.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={7.5} />
    </group>
  )
};

export default RoomModel;
useGLTF.preload('models/room.glb');
